default_stages: [ "pre-commit", "commit-msg", "pre-push" ]
default_language_version:
  python: python3


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: "End of file fixer"
      - id: debug-statements
        name: "Debug imports and breakpoints checker"
      - id: mixed-line-ending
        name: "Mixed line ending fixer"
      - id: check-yaml
        name: "Yaml checker"
        args: [ '--unsafe' ]
      - id: trailing-whitespace
        name: "Trailing whitespace fixer"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ "--select", "I", "--fix" ]
      # Run the formatter.
      - id: ruff-format
